pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: ec2-54-169-3-169.ap-southeast-1.compute.amazonaws.com
    username: ubuntu
    key_path: ./deploy/key.pem
    port: 22
    script:
      - eval "$(ssh-agent -s)"
      - ssh-add -k $HOME/.ssh/ssh_git_rsa
      - cd /var/www/html/web-server/
      - git pull origin master
    when:
      status: success

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/${SLACK_SERVICE}
    channel: devchannel
    username: incoming-webhook
    icon_url: https://unsplash.it/256/256/?random
    when:
      event: [ push ]

  backend:
    image: laradock/workspace:1.8-71
    group: laravel
    commands:
      - php -v
      - composer -V
      - /bin/bash ./deploy/env_config.sh --db-name ${PG_DB_DATABASE} --db-uname ${PG_DB_USERNAME} --db-pwd ${PG_DB_PASSWORD}
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
      - ./vendor/bin/phpunit
