pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: ec2-54-169-3-169.ap-southeast-1.compute.amazonaws.com
    username: ubuntu
    key_path: ./deploy/key.pem
    port: 22
    script:
      - eval "$(ssh-agent -s)"
      - ssh-add -k $HOME/.ssh/ssh_git_rsa
      - cd /var/www/html/web-server/
      - git pull origin master
    when:
      status: success

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/${SLACK_SERVICE}
    channel: devchannel
    username: incoming-webhook
    icon_url: https://unsplash.it/256/256/?random
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      # event: [ push ]
      status: [ success, failure ]

  backend:
    image: laradock/workspace:1.8-71
    group: laravel
    commands:
      - php -v && composer -V
      - /bin/bash deploy/env_config.sh --db-name dbname --db-uname postgres --db-pwd postgres
      - ls -la
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
      - echo "UNIT Testing" && ./vendor/bin/phpunit
      - echo "Acceptance Testing" && ./vendor/bin/codecept run acceptance -d

services:
  postgres:
    image: postgres:9.5.5
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  hub:
    image: selenium/hub:3.8.1-dubnium
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.8.1-dubnium
    environment:
      - HUB_HOST=hub
