pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: ec2-54-251-156-35.ap-southeast-1.compute.amazonaws.com
    username: ubuntu
    key_path: ./deploy/key.pem
    port: 22
    script:
      - cd /var/www/html/web-server/
      - git pull origin master
    when:
      status: success

  # docker:
  #   image: plugins/docker
  #   username: ${DOCKER_USERNAME}
  #   password: ${DOCKER_PASSWORD}
  #   email: ${DOCKER_EMAIL}
  #   repo: haidocker/drone-ci
  #   dockerfile: ./deploy/Dockerfile
  #   tags: latest

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/${SLACK_SERVICE}
    channel: devchannel
    username: incoming-webhook
    icon_url: https://unsplash.it/256/256/?random
    when:
      event: [ push ]

  clone:
    image: plugins/git
    recursive: true
    submodule_override:
      laravel54: https://github.com/minhhai8x/laravel54.git
  
  ecr-auth:
    image: omerxx/drone-ecr-auth
    pull: true
    privileged: true
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
      - docker pull ${AWS_ECR_REPO}

  build:
    image: ${AWS_ECR_REPO}

  ecr:
    image: plugins/ecr
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    repo: ${AWS_ECR_REPO}
    registry: ${AWS_ECR_REGISTRY}
    tags:
      - 1.0
    region: ap-southeast-1
    dockerfile: ./deploy/Dockerfile
