pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: ec2-54-169-3-169.ap-southeast-1.compute.amazonaws.com
    username: ubuntu
    key_path: ./deploy/key.pem
    port: 22
    script:
      - cd /var/www/html/web-server/
      - git pull origin master
    when:
      status: success

  # docker:
  #   image: plugins/docker
  #   username: ${DOCKER_USERNAME}
  #   password: ${DOCKER_PASSWORD}
  #   email: ${DOCKER_EMAIL}
  #   repo: haidocker/drone-ci
  #   dockerfile: ./deploy/Dockerfile
  #   tags: latest

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/${SLACK_SERVICE}
    channel: devchannel
    username: incoming-webhook
    icon_url: https://unsplash.it/256/256/?random
    when:
      event: [ push ]

  clone:
    image: plugins/git
    recursive: true
    submodule_override:
      laravel54: https://github.com/minhhai8x/laravel54.git

  # ecr:
  #   image: plugins/ecr
  #   access_key: ${AWS_ACCESS_KEY}
  #   secret_key: ${AWS_SECRET_KEY}
  #   repo: ${AWS_ECR_REPO}
  #   registry: ${AWS_ECR_REGISTRY}
  #   tags: latest
  #   region: ap-southeast-1
  #   dockerfile: ./deploy/Dockerfile

  notify:
    image: drillster/drone-email
    host: smtp.gmail.com
    username: ${EMAIL_UNAME}
    password: ${EMAIL_PWD}
    from: ${EMAIL_FROM}
    recipients: ['${RECIPIENT_EMAIL}']
    recipients_only: true
    skip_verify: true
    when:
      status: [ success ]
